title: Ravi Ramchandran
description: Principal Software Engineering Manager | AI Researcher | Tech Leader
lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
url: "https://rramchan12.github.io"
baseurl: ""
