name: Build and deploy Jekyll site to GitHub Pages

# Build and deploy the Jekyll site and publish to GitHub Pages when main branch is updated
# For user site repositories (username.github.io) GitHub Pages will serve the site from the root of the main branch,
# but this workflow builds the site and uses the Pages deployment actions to ensure consistent builds.

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: github-pages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install Bundler and dependencies
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Build the Jekyll site
        run: bundle exec jekyll build -d ./_site

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v4
        with:
          enablement: true

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: github-pages

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
